import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../Components/Shared/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Motor Merchants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
