import Head from "next/head";
import Hero from "../Components/Home/Hero";
import Products from "../Components/Home/Products";
import { GetStaticProps } from "next";
import Service from "../Components/Home/Service";
import Customer from "../Components/Home/Customer";
import Brand from "../Components/Home/Brand";
import FAQ from "../Components/Home/FAQ";
import Reviews from "../Components/Home/Reviews";

export interface ProductProps {
  _id: string;
  name: string;
  price: number;
  description: string;
  minOrder: number;
  available: number;
  ImgUrl: string;
}
export interface HomeProps {
  products: ProductProps[];
}

export default function Home({ products }: HomeProps) {
  return (
    <div className="mx-0 md:mx-[170px] bg-white mt-20">
      <Head>
        <title>Motor Merchants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Products products={products} />
      <Service />
      <Customer />
      <Brand />
      <FAQ />
      <Reviews />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async (): Promise<{
  props: HomeProps;
}> => {
  const data = await fetch("http://localhost:8000/products");
  const products = await data.json();
  return {
    props: { products },
  };
};
